# Naive Bayes

In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv(r'C:\Users\VIVEK\OneDrive\Desktop\AI-ML\CSV files\IRIS.csv')
df.head()

sepal_length  sepal_width  petal_length  petal_width      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [3]:
x = df.iloc[:,0:4].values
y = df.iloc[:,-1].values
print(x.shape)
print(y.shape)

(150, 4)
(150,)


In [4]:
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest = train_test_split(x,y,test_size=0.2,random_state=0)

In [5]:
from sklearn.preprocessing import StandardScaler
ss = StandardScaler()
xtrain = ss.fit_transform(xtrain)
xtest = ss.fit_transform(xtest)

In [6]:
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(xtrain,ytrain)

GaussianNB()

In [7]:
ypred = classifier.predict(xtest)

In [8]:
ypred

array(['Iris-virginica', 'Iris-versicolor', 'Iris-setosa',
       'Iris-virginica', 'Iris-setosa', 'Iris-virginica', 'Iris-setosa',
       'Iris-virginica', 'Iris-virginica', 'Iris-versicolor',
       'Iris-virginica', 'Iris-virginica', 'Iris-versicolor',
       'Iris-virginica', 'Iris-virginica', 'Iris-setosa',
       'Iris-virginica', 'Iris-versicolor', 'Iris-setosa', 'Iris-setosa',
       'Iris-virginica', 'Iris-versicolor', 'Iris-setosa', 'Iris-setosa',
       'Iris-virginica', 'Iris-setosa', 'Iris-setosa', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-setosa'], dtype='<U15')

In [9]:
s = np.sum(ypred != ytest)
s

6

In [10]:
from sklearn.metrics import confusion_matrix,classification_report,accuracy_score
print()
print('The accuracy of the model is:',accuracy_score(ytest,ypred)*100)
print()
print('Confusion Matrix :\n', confusion_matrix(ytest,ypred))
print()
print('Classification Report :\n',classification_report(ytest,ypred))


The accuracy of the model is: 80.0

Confusion Matrix :
 [[11  0  0]
 [ 0  7  6]
 [ 0  0  6]]

Classification Report :
                  precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        11
Iris-versicolor       1.00      0.54      0.70        13
 Iris-virginica       0.50      1.00      0.67         6

       accuracy                           0.80        30
      macro avg       0.83      0.85      0.79        30
   weighted avg       0.90      0.80      0.80        30

