Question 1:
--
Create an element-wise comparison (greater, greater_equal, less and less_equal) of two given arrays

In [1]:
# Numpy program for element wise comparison (Greater than)
import numpy as np
a1 = np.array([[1, 2, 3],[4, 5, 6]])
a2 = np.array([[9, 8, 7],[6, 5, 4]])
filter = a1 > a2
print(filter)

[[False False False]
 [False False  True]]


In [2]:
# Numpy program for element wise comparison (Greater than or equal to)
a1 = np.array([[1, 2, 3],[4, 5, 6]])
a2 = np.array([[9, 8, 7],[6, 5, 4]])
filter = a1 >= a2
print(filter)

[[False False False]
 [False  True  True]]


In [3]:
# Numpy program for element wise comparison (less than)
a1 = np.array([[1, 2, 3],[4, 5, 6]])
a2 = np.array([[9, 8, 7],[6, 5, 4]])
filter = a1 < a2
print(filter)

[[ True  True  True]
 [ True False False]]


In [4]:
# Numpy program for element wise comparison (less than or equal to)
a1 = np.array([[1, 2, 3],[4, 5, 6]])
a2 = np.array([[9, 8, 7],[6, 5, 4]])
filter = a1 <= a2
print(filter)

[[ True  True  True]
 [ True  True False]]


Question 2:
--
Write a NumPy program to create an array of 10 zeros,10 ones, 10 fives

In [5]:
# Numpy program to create an array of 10 zeros
z = np.zeros([1,10], dtype = np.int64)
print(z)

[[0 0 0 0 0 0 0 0 0 0]]


In [6]:
# Numpy program to create an array of 10 ones
o = np.ones([1,10], dtype = np.int64)
print(o)

[[1 1 1 1 1 1 1 1 1 1]]


In [7]:
# Numpy program to create an array of 10 fives
f = np.full([1,10],5)
print(f)

[[5 5 5 5 5 5 5 5 5 5]]


Question 3:
--
Write a NumPy program to compute sum of all elements, sum of each column and sum of each row of a
given array

In [8]:
# Numpy program to sum all the elemnts in an array
arr = np.array([[1, 2, 3],[4, 5, 6]])
sum_all_elements = np.sum(arr)
print(sum_all_elements)

21


In [9]:
# Numpy program to sum of each column elemnts in an array
arr = np.array([[1, 2, 3],[4, 5, 6]])
sum_column_elements = np.sum(arr, axis = 0)   # 1 + 4 = 5 ; 2 + 5 = 7 ; 3 + 6 = 9
print(sum_column_elements)

[5 7 9]


In [10]:
# Numpy program to sum of each row elemnts in an array
arr = np.array([[1, 2, 3],[4, 5, 6]])
sum_row_elements = np.sum(arr, axis = 1)       # 1 + 2 + 3 = 6 ;  4 + 5 + 6 =15
print(sum_row_elements)

[ 6 15]


Question 4:
--
Write a NumPy program to add, subtract, multiply, divide arguments element-wise.

In [11]:
# Creating Numpy arrays
a1 = np.array([[1, 2, 3],[4, 5, 6]])
a2 = np.array([[9, 8, 7],[6, 5, 4]])
print('The given arrays are\n {} \n and\n {}'.format(a1,a2))

The given arrays are
 [[1 2 3]
 [4 5 6]] 
 and
 [[9 8 7]
 [6 5 4]]


In [17]:
# numpy programe to add to arrays element wise
ad = np.add(a1,a2)          # ad = a1 + a2
print(ad)

[[10 10 10]
 [10 10 10]]


In [12]:
# numpy programe to subtract to arrays element wise
sub = np.subtract(a1,a2)    #  sub = a1 - a2
print(sub)

[[-8 -6 -4]
 [-2  0  2]]


In [13]:
# numpy programe to divide to arrays element wise
div = np.divide(a1,a2)      # div = a1 / a2
print(div)

[[0.11111111 0.25       0.42857143]
 [0.66666667 1.         1.5       ]]


In [14]:
# numpy programe to multiply to arrays element wise
mul = np.multiply(a1, a2)      # mul = a1 * a2
print(mul)

[[ 9 16 21]
 [24 25 24]]


Question 5:
--
Write a NumPy program to compute the trigonometric sine, cosine and tangent array of angles given in
degree.

In [15]:
# Numpy program to compute trigonometric sine
a1 = np.array([[1, 2, 3],[4, 5, 6]])
sin = np.sin(a1)
print(sin)

[[ 0.84147098  0.90929743  0.14112001]
 [-0.7568025  -0.95892427 -0.2794155 ]]


In [16]:
# Numpy program to compute trigonometric cosine
cos = np.cos(a1)
print(cos)

[[ 0.54030231 -0.41614684 -0.9899925 ]
 [-0.65364362  0.28366219  0.96017029]]


In [17]:
# Numpy program to compute trigonometric tan
tan = np.tan(a1)
print(tan)

[[ 1.55740772 -2.18503986 -0.14254654]
 [ 1.15782128 -3.38051501 -0.29100619]]
